Dev
stepancar-web-programming/2023-fall-lab-portfolio-chechetko-v.-v. pull request #5
Opened 2024-03-15 18:45 UTC by EternalVelard

Все исправил

2024-03-16 18:26 UTC, stepancar requested changes
Не хватает автоматизации проверок. В проекте нет eslint/stylelint. editorconfig

2024-03-20 12:22 UTC, EternalVelard commented
> Не хватает автоматизации проверок. В проекте нет eslint/stylelint. editorconfig

Все сделано

2024-03-20 23:46 UTC, stepancar requested changes
В проекте появились конфиги для eslint/stylelint, но как они запускаются, устанавливаются не ясно. На CI нет запуска никаких проверок.

2024-03-21 10:14 UTC, EternalVelard commented
> В проекте появились конфиги для eslint/stylelint, но как они запускаются, устанавливаются не ясно. На CI нет запуска никаких проверок.

Сделал

2024-03-21 14:35 UTC, stepancar requested changes
В пайплайне есть warnings
<img width="1478" alt="Screenshot 2024-03-21 at 07 35 33" src="https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-chechetko-v.-v./assets/2854910/685cf577-14c0-4dd1-8ea3-62f3ca5ed7e4">

2024-03-21 16:10 UTC, EternalVelard commented
> В пайплайне есть warnings <img alt="Screenshot 2024-03-21 at 07 35 33" width="1478" src="https://private-user-images.githubusercontent.com/2854910/315332830-685cf577-14c0-4dd1-8ea3-62f3ca5ed7e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzc3MTMsIm5iZiI6MTcxMTAzNzQxMywicGF0aCI6Ii8yODU0OTEwLzMxNTMzMjgzMC02ODVjZjU3Ny0xNGMwLTRkZDEtOGVhMy02MmYzY2E1ZWQ3ZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMTYxMDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTMxM2JkY2VlMGM5MjgzOGQwZmY1YmZhNGM0NjhlMTZlZmU4MThiYThiMmZiNjU0ZWM5ZDI2MWJkMDk2MDU2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l3i6quVPEdk1EI4xOKTB3iL9Fw1e_QGQWELodSbD3ZU">

исправил

2024-03-21 18:47 UTC, stepancar commented on about.html
> +    </style>
Неоднотипность подходов; Какие-то стили вынесены в css файл, какие-то определены тут

2024-03-21 18:48 UTC, stepancar commented on about.html
> +                                <img src="image/smb1.jpg" alt="1" />
пожалуйста, убедитесь в том, что назначение аттрибута alt вам понятно

2024-03-21 18:48 UTC, stepancar commented on footer.css
> +  .icons a{
Кажется вы не валидируете форматирование

2024-03-21 19:16 UTC, EternalVelard commented on about.html
> +    </style>
Исправил. Теперь все стили в css файлах

2024-03-21 19:20 UTC, EternalVelard commented on about.html
> +                                <img src="image/smb1.jpg" alt="1" />
Как понимаю alt содержит текстовое описание изображения. И если бы браузер у нас не читал их или в проекте его не было, вместо изображения и была это надпись. Alt не обязателен тут

2024-03-21 19:20 UTC, EternalVelard commented on footer.css
> +  .icons a{
Отформатировал все файлы

2024-03-21 19:25 UTC, EternalVelard commented on about.html
> +                                <img src="image/smb1.jpg" alt="1" />
По сути он даёт понять при отсутствие или отключении изображения в браузере, что это за изображение. В мое случае либо убрать, потому что 1,2,3 не очень информативно, либо как я и сделал более информативно и поменял названия

2024-03-21 19:27 UTC, EternalVelard commented on about.html
> +                                <img src="image/smb1.jpg" alt="1" />
Так же думаю можно это использовать для проверки работы слайдера, если бы изображения были отключены

2024-03-22 23:29 UTC, stepancar commented on about.html
> +                                <img src="image/smb1.jpg" alt="smb_train_photo1" />
Alt аттрибут должен содержать описание изображения на картинке. Слепой пользователь не сможет увидеть картинку на вашем сайте, но он сможет всеравно понять что перед ним если вы добавите описание. Скрин ридер прочитает текст. 
Тут вы можете увидеть как примерно слепые пользуются сайтами.
https://www.youtube.com/watch?v=RQiN1Hhrxu0
alt это всего лишь один из тегов чтобы обеспечить доступность web. Внесенные вами изменения не позволят понять что за контент smb_train_photo1 - не читаемая строка. возможно, поисковый робот с гибкой языковой моделью сможет разобраться, но обычные скрин ридеры - нет

2024-03-23 03:30 UTC, EternalVelard commented on about.html
> +                                <img src="image/smb1.jpg" alt="smb_train_photo1" />
Исправил сделал более информативно
![smb_photo1](https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-chechetko-v.-v./assets/87513856/5835332d-4add-48d5-be85-2e4312f16791)

2024-03-23 05:20 UTC, stepancar approved these changes

2024-03-23 05:20 UTC, merged